### PR TITLE
A fix for #280

### LINKED ISSUE #280: Khal at command should use new lines between fields
When using `khal at` there should be new lines between the title, location, description and repetition of the event like the event_description function of the Event class does when creating the string but the textwrap.wrap function filters these newlines.

### PR DESCRIPTION
**Pull request by libre-man**
This fixes #280 by first using splitlines() so that new lines are preserved.

### CODE REVIEW

**Comment by libre-man** [comment]
I'm sorry I forgot to specify a certain commit.

**Comment by geier** [comment]
You are not yet listed as an author in AUTHORS.txt, are you? Could you please add yourself?

I'll merge this afterwards.

**Comment by libre-man** [comment]
No I was not, I added myself.

**Comment by geier** [comment]
@libre-man Sorry for not being more responsive, I'll have a look at all your PRs on Monday at the very latest.

**Comment by geier** [comment]
Thanks!

**Pull request merged**
