### PR TITLE
Basic event export

### PR DESCRIPTION
**Pull request by fpytloun**
Very basic event export into ICS (eg. for sending as mail attachment).
Some possible enhancements:
- ask what to do if file already exists
- handle exception or at least say something if event is saved
- export from events list

Related to https://github.com/geier/khal/issues/43

### CODE REVIEW

**Comment by geier** [comment]
Hi @fpytloun and thank you for this pull request. I believe your PR is a nice improvement over the current situation (no export at all). Before I'm merging this, please add yourself to `AUTHORS.txt`.

**Comment by fpytloun** [comment]
Thank you :-)
I would like to get more familiar with the code and enhance it in near future - especially way of sending invitation via email which will make my life easier :-)

**Comment by fpytloun** [comment]
Updated the code to be able to export from events list by `e` keybinding.
It duplicates the code a little but I don't know better place where to put the export logic.

**Comment by hobarrera** [comment]
It **really** looks like lots of code should be deduped.  
Maybe the `Calendar` class would be a good place for the export code?

**Comment by fpytloun** [comment]
Most of the duplicated code is about UI interaction which probably can't be placed anywhere else.
The export code alone is only about this:
```
            export_path = os.path.expanduser(user_data.get_edit_text())
            try:
                with open(export_path, 'w') as fh:
                    fh.write(self.event.raw)
```
I will try to put this part into `Calendar` class.

**Comment by fpytloun** [comment]
I have put the `export_ics` code under `Event` as it basically only wraps `Event.raw`. It deduplicates the code a bit.

**Comment by geier** [comment]
@fpytloun it does work for me, is this good to merge?

**Comment by geier** [comment]
Regarding sending invitations per email: you are mostly there I guess, just save the file in /tmp and than run a (configurable) command like `mutt -a {file}`. But because one might want to configure this for several programs, the current keybinding config section might need to be redone.

If you need any help getting around, please get in touch with me.

**Comment by fpytloun** [comment]
@geier yes, I am thinking about making action configurable per-calendar using something like `xdg-open mailto:?subject=invitation_whatever&attachment=/tmp/invitation.ics` or `mutt -a` as you noted.
And still considering possibility of implementing real rfc2445 invitations.. :-)

Anyway this change is probably finished and ready for merge.

**Comment by geier** [comment]
alright, I'll merge this then. Thank you again!

**Pull request merged**
