### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Comment by untitaker** [comment]
@geier Please verify that the tests are now not too liberal.

**Comment by geier** [comment]
I think the tests are too loose now, we can produce pretty broken VTIMEZONE components without failing the tests now. 

I was thinking about giving freezegun a try (just learned about it this weekend).

**Comment by untitaker** [comment]
>I think the tests are too loose now, we can produce pretty broken VTIMEZONE components without failing the tests now.

Which ones, for example?

Syntactically invalid properties are unlikely to occur because icalendar takes care of that for us. The order of the properties doesn't matter, too, and it's also unlikely that we're putting a property into the wrong kind of component.

We could also parse either of them and compare their contents.

**Comment by geier** [comment]
The way it is now we cannot detect if standard or DST time is +0100 or +0200 (initially this was in the wrong order and we would not detect it with these tests)

**Comment by geier** [comment]
perhaps the best solution would be to use cached vtimezone components #146

**Comment by untitaker** [comment]
@geier Please review.

**Comment by geier** [comment]
I'm much happier with this, please merge if it does indeed work.

**Comment by untitaker** [comment]
Done.

**Pull request closed without merging**
