### PR TITLE
List libxslt1 as required when building lxml from source.

### LINKED ISSUE #227: Install instructions on webpage incomplete
I realize this is just a detail, but in the install instructions on the webpage it should say that if you install via pip without lxml, you need to have not only python and libxml2 headers, but also xslt1 headers (at least I had to install libxslt1-dev for the installation to succeed on Debian 7.8.

Thanks for your work!

### PR DESCRIPTION
**Pull request by hobarrera**
Closes #227.

### CODE REVIEW

**Comment by hobarrera** [comment]
Ignore this for a bit; something broken with my local repo (that I cloned a minute ago), and I'm seeing coming that shouldn't be there.

**Comment by geier** [comment]
Thanks and please merge after fixing those typos.

**Comment by untitaker** [comment]
@hobarrera any update?

**Comment by hobarrera** [comment]
Fixed (via `--amend`).

Sorry for the delay. I'm moving these days, and my ISP has screwed up leaving me for seven days with not internet. :(

**Comment by untitaker** [comment]
No worries, thanks for the patch!

**Pull request merged**
