### PR TITLE
Allow configuring the amount of days shown by default.

### PR DESCRIPTION
**Pull request by hobarrera**
This allow configuring a default value for the argument `--days N`.

The default behaviour is unchanged.

### CODE REVIEW

**Comment by hobarrera** [comment]
No feedback?

**Comment by untitaker** [comment]
Sorry for the late response, could you add a test in `cli_test` for this?

**Comment by geier** [comment]
Sadly I still had no time left for khal, I hope it gets better next week (same goes for #178 and #172 ).

**Comment by geier** [comment]
while this looks good, please add a test for it and fix the currently failing tests (you do NOT  need to fix `test_dt_two_tz`, that is my problem)

**Comment by hobarrera** [comment]
Yes, sorry, I've had a few busy days and haven't gotten around to it, but I'll add the tests and get back to you on this. :)

**Comment by hobarrera** [comment]
I just added a test for this configuration option, and updated the existing ones to use the default value.

**Comment by geier** [comment]
Two tests in `tests/settings_test.py` are still failing (and you might want to rebase to current master, but I can also do that after you fixed those tests)

**Comment by hobarrera** [comment]
You're right, sorry. Since some tests were failing, I'd only ran `cli_test` for simplicity. `settings_test` is now passing too.

**Comment by untitaker** [comment]
There's one `cli_test` failing.

**Comment by hobarrera** [comment]
Oops!

Yeah, it's the new one (I rebased). Fixed now.

**Comment by geier** [comment]
one more thing, please add yourself to `AUTHORS.txt`

**Comment by hobarrera** [comment]
Done, thanks.

**Comment by geier** [comment]
Thank you!

**Pull request merged**
