### PR TITLE
Update docs as discussed in #333.

### PR DESCRIPTION
**Pull request by lucc**

### CODE REVIEW

**Comment by geier** [comment]
Thank you, we'll merge this after your other one.

**Comment by geier** [comment]
Sorry, I missed something: please make these changes in `khal/settings/khal.spec` instead, `configspec.rst` gets generated from there on building the docs.

**Comment by lucc** [comment]
Will do.

Why do you store a generated file in git?

**Comment by geier** [comment]
Didn't remember, but Read The Docs couldn't generate that file (or I didn't know how). RTD builds are failing at the moment either way.

Thanks again!

**Pull request merged**
