### PR TITLE
Drop python2

### LINKED ISSUE #190: Review types of strings used internally
See https://github.com/geier/khal/pull/187

### LINKED ISSUE #302: Drop Python 2
OS/Distributions readiness to support python 3 only applications
===================

* :white_check_mark: Arch
* :white_check_mark: Fedora
*  :x:FreeBSD (no pre-build package available any more)
* :white_check_mark:: NetBSD/pkg.src 
* :question: openSUSE
* :white_check_mark: Debian/Ubuntu: there is no package anyway, but otherwise does look ready
* :white_check_mark: Gentoo
* what other (major) distributions/OSes are missing from this list?

**Feel free to edit this**

### PR DESCRIPTION
**Pull request by hobarrera**
If we want to merge this or not really depends on what we decide on #302.

In the meantime, I went ahead and did the basic cleanup to drop py27 and the compatibility layer we had for it. There's probably more, small, cleanups that we can do and will come across in future.

Note that pypy is compatible with python 3.2.5, so we can't use that.  
Also, some doc said the minimum version was 3.3, and other places said 3.4. ~~I've standardized it to 3.4; I guess the rest was outdated.~~ It's 3.3. See below.

Closes #302
Closes #257 (no-longer-valid)
Closes #190
Check how this affects #207, #256.

### CODE REVIEW

**Comment by untitaker** [comment]
`3.3` should work, also there's `pypy3` (not sure if it's production-ready)

**Comment by hobarrera** [comment]
Like I said, pypy3 is only python 3.2.5 compatible (hence <3.3).
Installation of some dependencies failed on it, so I didn't look any further.

**Comment by untitaker** [comment]
Argh, yes.

**Comment by untitaker** [comment]
:+

**Comment by hobarrera** [comment]
You're right, py33 works too. I've added it to the tests suite, and everything passes.

**Comment by hobarrera** [comment]
Is it okay to also remove these lines?

    # vim: set ts=4 sw=4 expandtab sts=4 fileencoding=utf-8:

I actually use vim too, but I think that most contributors should already have this configured this way. It's also present in very few files anyway, so anyone relying on this will break other files anyway.

**Comment by untitaker** [comment]
Yes, probably.

If we care about this http://editorconfig.org/ might be the way to go.

**Comment by geier** [comment]
Does python 3 assume files to be utf-8 encoded?

**Comment by hobarrera** [comment]
> Does python 3 assume files to be utf-8 encoded?

It does: https://docs.python.org/3/howto/unicode.html#the-string-type

**Comment by geier** [comment]
Than sure, let's get rid of those vim lines (it probably was me who put them there in the first place and I don't need them).

**Comment by geier** [comment]
do we need to add something to `setup.py` to indicate it's python 3 only?

Also, two weeks are nearly up :) and it looks like we won't loose too many users (I'll probably add a [short description on how to run khal from a virtualenv](http://lostpackets.de/blog/vdirsyncer-on-debian.html) later).

@hobarrera  feel free to merge this

**Comment by hobarrera** [comment]
> do we need to add something to setup.py to indicate it's python 3 only?

I changed the hashbang from `python` to `python3`. I also updated the classifiers, to pypi will reflect the python3-status.

**Pull request merged**
