### PR TITLE
Some UI refactoring (WIP)

### PR DESCRIPTION
**Pull request by untitaker**
This contains a few WIP changes to the UI. My goal is to make ikhal
behave like mutt: `q` or `esc` always brings the user back to the
previous screen. The event editor now has its own pane, as I felt that
the screen was getting too crowded.

Some internal classes have been revised, and some "convenience"
attributes have been removed.

Todo:

- [ ] Redesing the event editor
   - [x] introduce spacing at necessary places
   - [ ] somehow enable the user to save & exit without hitting
     down-arrow multiple times?
- [x] BUG: You can't edit events twice
- [ ] Don't re-scan calendars while saving
- [x] Don't allow editing for read-only calendars

### CODE REVIEW

**Comment by geier** [comment]
I'm not a fan of isolating the editor in its own pane as I want to see the other scheduled events on that day. But I agree that we don't need the calendar column, so I solution might be displaying all events scheduled on the day  in its own column.

eg: default view

    +---------------------------+----------------------+
    |     Mo Tu We Th Fr Sa Su  |  23.02.2015:         |
    | Feb 26 27 28 29 30 31  1  |  Event 1             |
    |   6  2  3  4  5  6  7  8  |  Event 2             |
    |   7  9 10 11 12 13 14 15  |                      |
    |   8 16 17 18 19 20 21 22  +----------------------+
    | Mar 23 24 25 26 27 28  1  |  Event Details       |
    |  10  2  3  4  5  6  7  8  |                      |
    |  11  9 10 11 12 13 14 15  |                      |
    |  12 16 17 18 19 20 21 22  |                      |
    |  13 23 24 25 26 27 28 29  |                      |
    +---------------------------+----------------------+
 
edit view:  

    +----------------------+----------------------+
    |  23.02.2015:         |  summary             |
    |  Event 1             |  start date xxx      |
    |  Event 2             |  end date XXX        |
    |                      |  description         |
    |                      |                      |
    |                      |                      |
    |                      |                      |
    |                      |                      |
    |                      |                      |
    |                      |                      |
    +----------------------+----------------------+

**Comment by untitaker** [comment]
Ok, I'd like to move today's events to the right of the edit view though, since reading direction is ltr.

**Comment by untitaker** [comment]
Just rebased and noticed the changes you've made re keybindings.

@geier Why is everything subclassing config now?

**Comment by untitaker** [comment]
@geier Now I just move the event list into a new view. Please review.

**Comment by geier** [comment]
@untitaker I'm subclassing Config to avoid handing the keybindings dict around. If you know a better way to achive that, I'm all for it.

**Comment by geier** [comment]
while I like the layout, I'm currently unsure if the calendar might not be useful anyway when editing events (e.g. looking for the next monday)

**Comment by untitaker** [comment]
I usually open a second calendar for that.

**Comment by geier** [comment]
you're right, never mind.

**Comment by untitaker** [comment]
@geier I avoided the global state of Config by simply passing everything explicitly. It didn't improve that much though. Maybe this could be improved with https://github.com/mitsuhiko/click/issues/292 ?

**Comment by untitaker** [comment]
I've now added a simple alert to the top-bar when the user tries to edit read-only events. Unfortunately the alert doesn't go away until the user switches panes. I thought about a nethack-like interface where the alert would go away after a few keystrokes.

**Comment by geier** [comment]
I really do like that, I think it would be nice to have that for deleting read-only events as well (instead of that RO flag)

**Comment by untitaker** [comment]
I'm done, the rest should be postponed. @geier may I merge?

**Comment by geier** [comment]
When changing the calendar an event belongs to I get the following exception:

      File "/home/cg/workspace/khal/khal/ui/__init__.py", line 750, in save
        self.accountchooser.account)
     AttributeError: 'Choice' object has no attribute 'account'

**Comment by geier** [comment]
also when switching to the event list, the currently selected date isn't highlighted anymore. As this was buggy before (something to do with empty event lists if I remember correctly) I'm still happy to merge this.

**Comment by untitaker** [comment]
>also when switching to the event list, the currently selected date isn't highlighted anymore

Yeah, see https://github.com/untitaker/khal/commit/3ad63d609851e92521b42f87b18365da387162b1, there is no code where this property change is reverted.

**Comment by untitaker** [comment]
Also, I fixed that bug.

**Comment by geier** [comment]
on editing I now get:

          File "/home/cg/.virtualenvs/khal/local/lib/python2.7/site-packages/urwid/listbox.py", line 987, in keypress
        key = focus_widget.keypress((maxcol,),key)
      File "/home/cg/workspace/khal/khal/ui/__init__.py", line 367, in keypress
        self.eventcolumn.edit(self.event)
      File "/home/cg/workspace/khal/khal/ui/__init__.py", line 473, in edit
        editor = EventEditor(self.pane, event)
      File "/home/cg/workspace/khal/khal/ui/__init__.py", line 641, in __init__
        decorate_choice
      File "/home/cg/workspace/khal/khal/ui/base.py", line 260, in __init__
        self.active = self._original = active
      File "/home/cg/workspace/khal/khal/ui/base.py", line 285, in active
        self.button = urwid.Button(self._decorate(self._active))
      File "/home/cg/workspace/khal/khal/ui/__init__.py", line 636, in decorate_choice
        return (c.color or '', c.name)
    AttributeError: 'str' object has no attribute 'color'

**Comment by untitaker** [comment]
Sorry, fixed in master.

**Comment by geier** [comment]
on changing calendars:

      File "/home/cg/workspace/khal/khal/ui/__init__.py", line 749, in save
         self.calendar_chooser.active)
      File "/home/cg/workspace/khal/khal/khalendar/khalendar.py", line 257, in change_collection
        self._calnames[new_collection].new(event)
    KeyError: <khal.khalendar.khalendar.Calendar object at 0x7f6a9566ab10>

**Comment by untitaker** [comment]
Fixed that too :S

**Comment by geier** [comment]
thanks

**Pull request merged**
