### PR TITLE
khal calendar: Strip colors if not isatty

### LINKED ISSUE #338: feature request: 'clean' output for use in conky
Hi,

I've been running khal in conky with the following line:  
`${execpi 36000 khal}`  

Which while it works, gives a lot of garbage on the display. I'd be interested to see a CLI flag for khal that would give a conky-compatable output. Picture attached is how it looks right now (Top) with how it would ideally look (Bottom) - I did this by simply piping the khal output to a text file and manually deleting the extras for the bold/colourful characters.  

Apparently this is an issue gcalcli has too (Which I discovered when searching for a fix) and seems to be a limitation with Conky not supporting the special characters used.

### PR DESCRIPTION
**Pull request by untitaker**
Fix #338

Click already does this work for us, but not on bytes.

### CODE REVIEW

**Comment by hobarrera** [comment]
I'd really like to have a `--colour` flag to force colouring (which is useful when grepping).

**Comment by untitaker** [comment]
We can add that later as well -- for now, let's do what the other commands (e.g. agenda) already do.

**Comment by geier** [comment]
While this is a quick fix, I think we should not generate colors in the first place when we don't need them (especially calendar coloring can be very expensive).

**Comment by hobarrera** [comment]
> While this is a quick fix, I think we should not generate colors in the first place when we don't need them (especially calendar coloring can be very expensive).

This makes me wonder if we shouldn't store calendar colours in the db, and somehow generate colours though a db query (which would be quite more efficient).

**Comment by untitaker** [comment]
I don't know if that's sufficiently advantageous to warrant the added complexity. db is necessary due to time-range queries.

**Comment by untitaker** [comment]
Let's do the color stripping for another PR. Click's logic regarding whether to strip colors is quite complex, and I'm not comfortable introducing logic in khal that works in parallel. I'd much rather add an API to click that exposes its decision.

**Pull request merged**
