### PR TITLE
[WIP] use pager for agenda

### PR DESCRIPTION
**Pull request by untitaker**
https://github.com/geier/khal/issues/93

### CODE REVIEW

**Comment by geier** [comment]
you'll probably need to edit test_printformats() in `tests/cli_tests.py`.

**Comment by coachshea** [comment]
Thank you. I will do that.

**Comment by untitaker** [comment]
Wait what, this is the wrong PR.

**Comment by geier** [comment]
sorry, don't know how this happened.

**Comment by geier** [comment]
I have just deleted some comments that should have gone into another thread (were resolved anyway.

**Comment by untitaker** [comment]
I don't work on this anymore and it's garbage anyway, closing.

**Pull request closed without merging**
