### PR TITLE
Refactor tox.ini

### LINKED ISSUE #317: travis ci: style tests run py.tests as well
since the introduction of the NEGTZ variant, the style tests that should only run flake8 also run py.test (e.g. [945.2](https://travis-ci.org/geier/khal/jobs/98964527)). @hobarrera @untitaker If one of you knows their way around travis, could you have a look?

### PR DESCRIPTION
**Pull request by untitaker**
Fix #317

### CODE REVIEW

**Comment by geier** [comment]
r as in meRge? Sure and thank you very much!

**Comment by untitaker** [comment]
`r?` as in review. It's used heavily in `rust-lang/rust`, might as well use it outside! :O

**Comment by geier** [comment]
lgtm :) does what it's supposed to do and looks cleaner than before.

**Pull request merged**
