### PR TITLE
Khal doesn't pick arbitrary calendars as default

### PR DESCRIPTION
**Pull request by untitaker**
See #215

### CODE REVIEW

**Comment by geier** [comment]
I'm not sure if `-c` is the best choice for the new parameter, I actually prefer it, if `-c` is only used as short form of `--config` (this is why I initially chose `-a` for **a**ctivating calendars, the only suggestion I have is also using `-a`, but I guess that is not ideal either.

Anyone else want to weigh in?

**Comment by untitaker** [comment]
I'll just rename it to `-a`. Come to think of it I think consistency with other options is more important.

**Comment by untitaker** [comment]
Done!

**Comment by geier** [comment]
Thanks and merged!

**Pull request merged**
