### PR TITLE
Refactor khalendar.expand

### PR DESCRIPTION
**Pull request by untitaker**
- Don't modify the vevent -- I think there was a bug where we strip the
  timezone information from DTSTART, but never add it back.

- Remove special return-path for events without RRULEs

### CODE REVIEW

**Comment by untitaker** [comment]
Linthub is for Python 2 code. It doesn't recognize Python 3 syntax.

**Comment by geier** [comment]
I looked at this just now and I think it's okay, but because this is one of the most complex functions in all of khal, I'm going to do it again (hopefully tomorrow) before merging it.

**Comment by untitaker** [comment]
Force-push to update commit status

**Comment by geier** [comment]
looks good, please rebase and merge

**Pull request merged**
